### ISSUE TITLE
Investigacion Previa Recursos de Proyecto

### ISSUE THREAD

**Issue by nmartinezPGC** [nmartinezPGC/template_pgc#101]
Investigar técnicas de guardado de recursos (pdf, xls, png etc.) en:
1) Base de datos
2) Disco Duro - Url
3) Base64 - Disco Duro

Incorporar material visual de ejemplos de uso.

**Comment by RicardoPavonPgc2018** [comment]
prueba

**Comment by RicardoPavonPgc2018** [comment]
[Introducción.docx](https://github.com/nmartinezPGC/template_pgc/files/3049717/Introduccion.docx)
