### ISSUE TITLE
Ingreso de Parametros | Vida Mejor y Plan de Nacion

### ISSUE THREAD

**Issue by nmartinezPGC** [nmartinezPGC/template_pgc#103]
Ingresar los Parámetros de Programas de Nación:
1) Plan de Nación
2) Vida Mejor

**Comment by GabrielCallejasPgc** [comment]
Estimado Nahum 
Tengo a bien comentarle que he finalizado de registrar a la Base de Datos los siguientes Programas:
1.- Creación de los Tipos de Programas:
1.1 Visión de País
1.2 Plan de Nación
1.3 Políticas Públicas y Estrategias Nacionales 
1.4 Vida Mejor
Adicionalmente se ingreso los Indicadores de Vida Mejor y los Indicadores de Plan de Nación. Un aproximado de 100 campos ingresados.

Atentamente,

GcallejasG
